-- CreateTable
CREATE TABLE `DataToko` (
    `id` VARCHAR(191) NOT NULL,
    `query` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `name_for_emails` VARCHAR(191) NOT NULL,
    `subtypes` VARCHAR(191) NULL,
    `category` VARCHAR(191) NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `address` TEXT NOT NULL,
    `street` VARCHAR(191) NULL,
    `city` VARCHAR(191) NOT NULL,
    `county` VARCHAR(191) NULL,
    `state` VARCHAR(191) NOT NULL,
    `state_code` VARCHAR(191) NULL,
    `postal_code` INTEGER NULL,
    `country` VARCHAR(191) NOT NULL,
    `country_code` VARCHAR(191) NOT NULL,
    `latitude` DOUBLE NOT NULL,
    `longitude` DOUBLE NOT NULL,
    `h3` VARCHAR(191) NULL,
    `time_zone` VARCHAR(191) NOT NULL,
    `plus_code` VARCHAR(191) NULL,
    `area_service` BOOLEAN NOT NULL,
    `rating` DOUBLE NULL,
    `reviews` INTEGER NOT NULL DEFAULT 0,
    `reviews_link` TEXT NULL,
    `reviews_tags` JSON NULL,
    `reviews_per_score` JSON NOT NULL,
    `reviews_per_score_1` INTEGER NOT NULL DEFAULT 0,
    `reviews_per_score_2` INTEGER NOT NULL DEFAULT 0,
    `reviews_per_score_3` INTEGER NOT NULL DEFAULT 0,
    `reviews_per_score_4` INTEGER NOT NULL DEFAULT 0,
    `reviews_per_score_5` INTEGER NOT NULL DEFAULT 0,
    `photos_count` INTEGER NOT NULL DEFAULT 0,
    `photo` TEXT NULL,
    `street_view` TEXT NULL,
    `logo` TEXT NULL,
    `located_in` VARCHAR(191) NULL,
    `located_google_id` VARCHAR(191) NULL,
    `business_status` VARCHAR(191) NOT NULL,
    `working_hours` JSON NOT NULL,
    `working_hours_csv_compatible` TEXT NULL,
    `other_hours` JSON NULL,
    `popular_times` JSON NULL,
    `typical_time_spent` VARCHAR(191) NULL,
    `range` VARCHAR(191) NULL,
    `prices` VARCHAR(191) NULL,
    `reservation_links` JSON NULL,
    `booking_appointment_link` TEXT NULL,
    `menu_link` TEXT NULL,
    `order_links` JSON NULL,
    `about` JSON NULL,
    `description` TEXT NULL,
    `posts` JSON NULL,
    `verified` BOOLEAN NOT NULL DEFAULT false,
    `owner_id` VARCHAR(191) NULL,
    `owner_title` VARCHAR(191) NULL,
    `owner_link` TEXT NULL,
    `location_link` TEXT NULL,
    `location_reviews_link` TEXT NULL,
    `place_id` VARCHAR(191) NOT NULL,
    `google_id` VARCHAR(191) NOT NULL,
    `cid` VARCHAR(191) NULL,
    `kgmid` VARCHAR(191) NULL,
    `reviews_id` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `DataToko_place_id_key`(`place_id`),
    UNIQUE INDEX `DataToko_google_id_key`(`google_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
